export const Strings = {
  Login: 'Zaloguj się',
  Username: 'Nazwa użytkownika',
  Password: 'Hasło',
  OldPassword: 'Stare hasło',
  NewPassword: 'Nowe hasło',
  RepeatNewPassword: 'Powtórz nowe hasło',
  Change: 'Zmień',
  ToxPl: 'ToxPl',
  AlreadyLogged: 'Już zalogowano',
  Logout: 'Wyloguj się',
  Me: 'Ja',
  FullName: 'Imię i nazwisko',
  FirstName: 'Imię',
  LastName: 'Nazwisko',
  Rank: 'Ranga',
  Email: 'E-mail',
  PhoneNumber: 'Numer telefonu',
  Serviceman: 'Serwisant',
  Manager: 'Menadzer',
  Admin: 'Administrator',
  Clients: 'Klienci',
  Name: 'Nazwa',
  Street: 'Ulica',
  PostalCode: 'Kod pocztowy',
  City: 'Miasto',
  Address: 'Adres',
  List: 'Lista',
  Add: 'Dodaj',
  Done: 'Zrobione',
  Staff: 'Pracownicy',
  Contact: 'Kontakt',
  Jobs: 'Zlecenia',
  AddContact: 'Dodaj kontakt',
  Edit: 'Edytuj',
  Ok: 'Ok',
  SessionExpired: 'Sesja wygasła. Zaloguj się',
  InternalError: 'Wystąpił wewnętrzny błąd serwera',
  UnknownError: 'Wystąpił niezidentyfikowany błąd',
  NoSuchUserOrBadPassword: 'Został podany zły login lub hasło.',
  Devices: 'Urządzenia',
  Device: 'Urządzenie',
  AddDevice: 'Dodaj urządzenie',
  DeviceType: 'Typ urządzenia',
  DeviceDenotement: 'Oznaczenie',
  SerialNumber: 'Numer seryjny',
  NoSuchClient: 'Podany klient nie istnieje',
  NoSuchJob: 'Podane zlecenie nie istnieje',
  NotFound: 'Nie zaleziono',
  Client: 'Klient',
  Owner: 'Właściciel',
  Save: 'Zapisz',
  AddJob: 'Dodaj zlecenie',
  Applicant: 'Zgłaszający',
  CreatedAt: 'Zgłoszono',
  State: 'Status',
  Created: 'Utworzono',
  Registered: 'Zarejestrowano',
  Diagnosed: 'Zdiagnozowano',
  Ordered: 'Złożono zamówienie',
  Finished: 'Ukończono',
  Closed: 'Zamknięto',
  Deleted: 'Usunięto',
  Job: 'Zlecenie',
  Dispatcher: 'Przyjmujący',
  Overview: 'Przegląd',
  JobRegister: 'Rejestrowanie zgłoszenia',
  JobDiagnose: 'Diagnoza',
  JobRegisterType: 'Rodzaj zgłoszenia',
  PostWarranty: 'Pogwarancyjny',
  Warranty: 'Gwarancyjny',
  PlaceOfRealisation: 'Miejsce realizacji',
  Description: 'Opis',

  hydraulicNominalDimension: 'Tłoczysko cz. hydrauliczna wymiar nominalny',
  th01: 'th01',
  th02: 'th02',
  th03: 'th03',
  th91: 'th91',
  th92: 'th92',
  th93: 'th93',

  pneumaticNominalDimension: 'Tłoczysko cz. pneumatyczna wymiar nominalny',
  tp01: 'tp01',
  tp02: 'tp02',
  tp03: 'tp03',
  tp91: 'tp91',
  tp92: 'tp92',
  tp93: 'tp93',

  plungerNominalDimension: 'Nurnik wymiar nominalny',
  n01: 'n01',
  n02: 'n02',
  n03: 'n03',
  n91: 'n91',
  n92: 'n92',
  n93: 'n93',

  PartsToReplace: 'Części do wymiany',
  EstimatedRepairTime: 'Szacowany czas naprawy',
  ExpertiseDate: 'Data expertyzy',

  RepairType: 'Typ naprawy',
  Free: 'Darmowa',
  Paid: 'Płatna',

  Order: 'Zamówienie',
  NumberSAP: 'Numer SAP',
  PurchaseOrder: 'Numer zamówienia sprzedarzowego',
  ClientsOrder: 'Identyfikator zamówienia klienta',

  Completion: 'Zakończenie',
  CompletionDate: 'Data zakończenia',
  RepairTime: 'Czas naprawy',
  Annotations: 'Uwagi końcowe',
  Registration: 'Rejestracja',
  NoSuchUser: 'Podany użytkownik nie istnieje',
  BadPassword: 'Złe hasło',
  PasswordsNotEqual: 'Hasła nie są identyczne'
};
