export const Strings = {
  Login: 'Zaloguj się',
  Username: 'Nazwa użytkownika',
  Password: 'Hasło',
  ToxPl: 'ToxPl',
  AlreadyLogged: 'Już zalogowano',
  Logout: 'Wyloguj się',
  Me: 'Ja',
  FullName: 'Imię i nazwisko',
  FirstName: 'Imię',
  LastName: 'Nazwisko',
  Rank: 'Ranga',
  Email: 'E-mail',
  PhoneNumber: 'Numer telefonu',
  Serviceman: 'Serwisant',
  Manager: 'Menadzer',
  Admin: 'Administrator',
  Clients: 'Klienci',
  Name: 'Nazwa',
  Street: 'Ulica',
  PostalCode: 'Kod pocztowy',
  City: 'Miasto',
  List: 'Lista',
  Add: 'Dodaj',
  Done: 'Zrobione',
  Staff: 'Kontakty',
  Contact: 'Kontakt',
  Jobs: 'Zlecenia',
  AddContact: 'Dodaj kontakt',
  Edit: 'Edytuj',
  Ok: 'Ok',
  SessionExpired: 'Sesja wygasła. Zaloguj się',
  InternalError: 'Wystąpił wewnętrzny błąd serwera',
  UnknownError: 'Wystąpił niezidentyfikowany błąd',
  NoSuchUserOrBadPassword: 'Został podany zły login lub hasło.',
  Devices: 'Urządzenia',
  Device: 'Urządzenie',
  AddDevice: 'Dodaj urządzenie',
  DeviceType: 'Typ urządzenia',
  DeviceDenotement: 'Oznaczenie',
  SerialNumber: 'Numer seryjny',
  NoSuchClient: 'Podany klient nie istnieje',
  NoSuchJob: 'Podane zlecenie nie istnieje',
  NotFound: 'Nie zaleziono',
  Client: 'Klient',
  Owner: 'Właściciel',
  Save: 'Zapisz',
  AddJob: 'Dodaj zlecenie',
  Applicant: 'Zgłaszający',
  CreatedAt: 'Zgłoszono',
  State: 'Status',
  Created: 'Utworzono',
  Registered: 'Zarejestrowano',
  Diagnosed: 'Zdiagnozowano',
  Ordered: 'Złożono zamówienie',
  Finished: 'Ukończono',
  Closed: 'Zamknięto',
  Deleted: 'Usunięto',
  Job: 'Zlecenie',
  Dispatcher: 'Przyjmujący',
  Overview: 'Przegląd',
  JobRegister: 'Rejestrowanie zgłoszenia',
  JobRegisterType: 'Rodzaj zgłoszenia',
  PostWarranty: 'Pogwarancyjny',
  Warranty: 'Gwarancyjny',
  PlaceOfRealisation: 'Miejsce realizacji',
  Description: 'Opis'
};
