export const Strings = {
  Login: 'Zaloguj się',
  Username: 'Nazwa użytkownika',
  Password: 'Hasło',
  ToxPl: 'ToxPl',
  AlreadyLogged: 'Już zalogowano',
  Logout: 'Wyloguj się',
  Me: 'Ja',
  FullName: 'Imię i nazwisko',
  FirstName: 'Imię',
  LastName: 'Nazwisko',
  Rank: 'Ranga',
  Email: 'E-mail',
  PhoneNumber: 'Numer telefonu',
  Serviceman: 'Serwisant',
  Manager: 'Menadzer',
  Admin: 'Administrator',
  Clients: 'Klienci',
  Name: 'Nazwa',
  Street: 'Ulica',
  PostalCode: 'Kod pocztowy',
  City: 'Miasto',
  List: 'Lista',
  Add: 'Dodaj',
  Done: 'Zrobione',
  Staff: 'Kontakty',
  Contact: 'Kontakt',
  Events: 'Zlecenia',
  AddContact: 'Dodaj kontakt',
  Edit: 'Edytuj',
  Ok: 'Ok'
};
